### ISSUE TITLE
Update Git releases

### ISSUE THREAD

**Issue by omsai** [ma-tech/Woolz#2]
It would be wonderful if the [releases could be propagated to Git](https://help.github.com/articles/creating-releases/), so that tarballs can be downloaded and compiled from source

At the minute the [latest release is listed as 1.5.0](https://github.com/ma-tech/Woolz/releases), whereas the git history indicates version 1.6.3 is the latest.

**Comment by ma-tech** [comment]
Thanks for the reminder, now done.
